apiVersion: 1

groups:
  - name: gnaf-service-alerts
    interval: 30s
    rules:
      - uid: gnaf-high-response-time
        title: High Response Time Alert
        condition: B
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: histogram_quantile(0.95, rate(gnaf_http_request_duration_seconds_bucket[5m]))
              interval: ""
              refId: A
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [1.0]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              expression: A > 1.0
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: "95th percentile response time is {{ $value }}s, which exceeds 1 second threshold"
          summary: "High response time detected for G-NAF Address Service"
        labels:
          severity: warning
          service: gnaf-address-service

      - uid: gnaf-low-cache-hit-ratio
        title: Low Cache Hit Ratio Alert
        condition: B
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: gnaf_cache_hit_ratio{cache_layer="overall"} * 100
              interval: ""
              refId: A
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [70]
                    type: lt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: avg
                  type: query
              expression: A < 70
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          description: "Overall cache hit ratio is {{ $value }}%, which is below 70% threshold"
          summary: "Low cache hit ratio for G-NAF Address Service"
        labels:
          severity: warning
          service: gnaf-address-service

      - uid: gnaf-high-error-rate
        title: High Error Rate Alert
        condition: B
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: (rate(gnaf_http_requests_total{status_code=~"4..|5.."}[5m]) / rate(gnaf_http_requests_total[5m])) * 100
              interval: ""
              refId: A
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [5]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: avg
                  type: query
              expression: A > 5
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 30s
        annotations:
          description: "Error rate is {{ $value }}%, which exceeds 5% threshold"
          summary: "High error rate detected for G-NAF Address Service"
        labels:
          severity: critical
          service: gnaf-address-service

      - uid: gnaf-dataset-unhealthy
        title: G-NAF Dataset Unhealthy
        condition: B
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: prometheus
            model:
              expr: gnaf_dataset_health
              interval: ""
              refId: A
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [1]
                    type: lt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              expression: A < 1
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold
        noDataState: Alerting
        execErrState: Alerting
        for: 1m
        annotations:
          description: "G-NAF dataset health status is {{ $value }}, indicating dataset issues"
          summary: "G-NAF dataset is unhealthy or unavailable"
        labels:
          severity: critical
          service: gnaf-address-service

      - uid: gnaf-db-connections-high
        title: High Database Connections Alert
        condition: B
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: gnaf_db_connections_active + gnaf_db_connections_idle
              interval: ""
              refId: A
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [18]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: avg
                  type: query
              expression: A > 18
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: "Database connections are {{ $value }}/20, nearing pool limit"
          summary: "High database connection usage for G-NAF Address Service"
        labels:
          severity: warning
          service: gnaf-address-service