version: '3.8'

services:
  redis-1:
    image: redis:7-alpine
    container_name: gnaf-redis-1
    command: redis-server /etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes-6379.conf --cluster-node-timeout 5000 --appendonly yes --port 6379
    ports:
      - "6379:6379"
      - "16379:16379"
    volumes:
      - ./redis/redis-1.conf:/etc/redis/redis.conf
      - redis-1-data:/data
    networks:
      - gnaf-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis-2:
    image: redis:7-alpine
    container_name: gnaf-redis-2
    command: redis-server /etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes-6380.conf --cluster-node-timeout 5000 --appendonly yes --port 6380
    ports:
      - "6380:6380"
      - "16380:16380"
    volumes:
      - ./redis/redis-2.conf:/etc/redis/redis.conf
      - redis-2-data:/data
    networks:
      - gnaf-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis-3:
    image: redis:7-alpine
    container_name: gnaf-redis-3
    command: redis-server /etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes-6381.conf --cluster-node-timeout 5000 --appendonly yes --port 6381
    ports:
      - "6381:6381"
      - "16381:16381"
    volumes:
      - ./redis/redis-3.conf:/etc/redis/redis.conf
      - redis-3-data:/data
    networks:
      - gnaf-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis-4:
    image: redis:7-alpine
    container_name: gnaf-redis-4
    command: redis-server /etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes-6382.conf --cluster-node-timeout 5000 --appendonly yes --port 6382
    ports:
      - "6382:6382"
      - "16382:16382"
    volumes:
      - ./redis/redis-4.conf:/etc/redis/redis.conf
      - redis-4-data:/data
    networks:
      - gnaf-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis-5:
    image: redis:7-alpine
    container_name: gnaf-redis-5
    command: redis-server /etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes-6383.conf --cluster-node-timeout 5000 --appendonly yes --port 6383
    ports:
      - "6383:6383"
      - "16383:16383"
    volumes:
      - ./redis/redis-5.conf:/etc/redis/redis.conf
      - redis-5-data:/data
    networks:
      - gnaf-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis-6:
    image: redis:7-alpine
    container_name: gnaf-redis-6
    command: redis-server /etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes-6384.conf --cluster-node-timeout 5000 --appendonly yes --port 6384
    ports:
      - "6384:6384"
      - "16384:16384"
    volumes:
      - ./redis/redis-6.conf:/etc/redis/redis.conf
      - redis-6-data:/data
    networks:
      - gnaf-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis-cluster-init:
    image: redis:7-alpine
    container_name: gnaf-redis-cluster-init
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    networks:
      - gnaf-network
    command: >
      sh -c "
        echo 'Waiting for Redis nodes to start...' &&
        sleep 10 &&
        redis-cli --cluster create 
          redis-1:6379 
          redis-2:6380 
          redis-3:6381 
          redis-4:6382 
          redis-5:6383 
          redis-6:6384 
          --cluster-replicas 1 
          --cluster-yes &&
        echo 'Redis cluster initialized successfully'
      "
    restart: "no"

  redis-sentinel-1:
    image: redis:7-alpine
    container_name: gnaf-redis-sentinel-1
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    volumes:
      - ./redis/sentinel-1.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-cluster-init
    networks:
      - gnaf-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  redis-sentinel-2:
    image: redis:7-alpine
    container_name: gnaf-redis-sentinel-2
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26380:26379"
    volumes:
      - ./redis/sentinel-2.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-cluster-init
    networks:
      - gnaf-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  redis-sentinel-3:
    image: redis:7-alpine
    container_name: gnaf-redis-sentinel-3
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26381:26379"
    volumes:
      - ./redis/sentinel-3.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-cluster-init
    networks:
      - gnaf-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  redis-1-data:
  redis-2-data:
  redis-3-data:
  redis-4-data:
  redis-5-data:
  redis-6-data:

networks:
  gnaf-network:
    driver: bridge