cluster.name: "gnaf-cluster"
network.host: 0.0.0.0
discovery.type: single-node
xpack.security.enabled: false
xpack.monitoring.collection.enabled: false

# Index lifecycle management
indices.lifecycle.history_index_enabled: false

# Index retention - delete daily indices after 7 days
action.auto_create_index: "+gnaf-logs-*,+gnaf-alerts-*,-*"

# Prevent excessive log indexing
index.refresh_interval: 30s
index.translog.flush_threshold_size: 1gb

# Disk usage thresholds
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%
cluster.routing.allocation.disk.watermark.flood_stage: 95%