global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gnaf-address-service'
    static_configs:
      - targets: ['host.docker.internal:3000']  # Your dev server
    metrics_path: '/api/v1/health/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']  # Optional: if you want system metrics