global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gnaf-address-service'
    static_configs:
      - targets: ['10.76.2.71:3001']  # Your dev server (Linux host IP)
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.76.2.71:9100']  # Optional: if you want system metrics